//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp_autósiskola.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExcelFajlHelye {
            get {
                return ((string)(this["ExcelFajlHelye"]));
            }
            set {
                this["ExcelFajlHelye"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KepzesiSablon {
            get {
                return ((string)(this["KepzesiSablon"]));
            }
            set {
                this["KepzesiSablon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KeszWord {
            get {
                return ((string)(this["KeszWord"]));
            }
            set {
                this["KeszWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool wordMegnyitasa {
            get {
                return ((bool)(this["wordMegnyitasa"]));
            }
            set {
                this["wordMegnyitasa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ExcelOldal {
            get {
                return ((int)(this["ExcelOldal"]));
            }
            set {
                this["ExcelOldal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExcelFajlMasolata {
            get {
                return ((string)(this["ExcelFajlMasolata"]));
            }
            set {
                this["ExcelFajlMasolata"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int oldalszam {
            get {
                return ((int)(this["oldalszam"]));
            }
            set {
                this["oldalszam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ekezetek {
            get {
                return ((bool)(this["ekezetek"]));
            }
            set {
                this["ekezetek"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool szokoz {
            get {
                return ((bool)(this["szokoz"]));
            }
            set {
                this["szokoz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Érd")]
        public string kiallitasiHely {
            get {
                return ((string)(this["kiallitasiHely"]));
            }
            set {
                this["kiallitasiHely"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool helyIdo {
            get {
                return ((bool)(this["helyIdo"]));
            }
            set {
                this["helyIdo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool honapBetu {
            get {
                return ((bool)(this["honapBetu"]));
            }
            set {
                this["honapBetu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en-US")]
        public string nyelv {
            get {
                return ((string)(this["nyelv"]));
            }
            set {
                this["nyelv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1;2;3;4;5;7;8;16;14;17;20;14;15;18;19;30;11;0;foutŁ1;0;3;2;4;5;6;11;12;14;18;12;1" +
            "3;15;0;0;9;10;abc")]
        public string tablaSync {
            get {
                return ((string)(this["tablaSync"]));
            }
            set {
                this["tablaSync"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int comboIndex {
            get {
                return ((int)(this["comboIndex"]));
            }
            set {
                this["comboIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ujTanuloIdo {
            get {
                return ((bool)(this["ujTanuloIdo"]));
            }
            set {
                this["ujTanuloIdo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2030")]
        public string iskolaAzonosito {
            get {
                return ((string)(this["iskolaAzonosito"]));
            }
            set {
                this["iskolaAzonosito"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Főút Autósiskola")]
        public string iskolaNev {
            get {
                return ((string)(this["iskolaNev"]));
            }
            set {
                this["iskolaNev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Érd, Fő Utca 52.")]
        public string iskolaCim {
            get {
                return ((string)(this["iskolaCim"]));
            }
            set {
                this["iskolaCim"] = value;
            }
        }
    }
}
